### ISSUE TITLE
Cancelling an issue creation still creates issue

### ISSUE THREAD

**Issue by domtronn** [domtronn/magit-gh-issues.el#28]
When an issue has content, pressing C-c C-k (with-editor-cancel) still creates the issue... I guess because even when cancelling the issue it gives the output to ghi regardless of the status

**Comment by domtronn** [comment]
I think there's some improvement that can be made for this issue, however I've managed to get this functional in [0.2.2](https://github.com/domtronn/magit-gh-issues.el/releases/tag/0.2.2).

I'd _ultimately_ like to cancel the `ghi` call rather than just remove the content from the editor so that it doesn't perform the action...

**Comment by AlexChesters** [comment]
This bug actually seems like its a bug with `ghi`, rather than `magit-gh-issues`
