### ISSUE TITLE
# Please explain the issue. The first line will become the title. Trailing

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/magit-gh-issues.el#42]
# lines starting with '#' (like these) will be ignored, and empty messages will
# not be submitted. Issues are formatted with GitHub Flavored Markdown (GFM):
# http://github.github.com/github-flavored-markdown

**Comment by domtronn** [comment]
Okay, I get your point :neutral_face:

**Comment by domtronn** [comment]
Although, I can't reproduce this, can you give me some steps to try and do this?
For me `ghi` just responds with

> There's no issue?

And one doesn't get created? :sweat_smile:

**Comment by AlexChesters** [comment]
Yeah, this was me breaking `ghi` for 1.0.0, 1.0.2 fixes this :smile:
