### ISSUE TITLE
Perform issue actions on multiple issues at once

### ISSUE THREAD

**Issue by domtronn** [domtronn/magit-gh-issues.el#53]
In `magit` you can perform actions on _multiple_ things at once, for example, stage multiple files for commit, revert multiple files etc.

A lot of actions don't make sense on multiple commits, however I'd like to investigate _how_ to get and perform actions on multiple `magit` objects.

As far as I've thought of, the following actions are the only ones that it would make sense to perform on multiple things at once.
- Closing Issues
- Assigning People to Issues _(dependent on #41)_
- Adding Labels

**Comment by domtronn** [comment]
I think this is fixed now...

@AlexChesters, could you do a pull and let me know if this fixes the issue?

**Comment by AlexChesters** [comment]
Assigning milestones to an issue?

**Comment by domtronn** [comment]
Sure, that's a valid one as well. :smile:

I think the biggest thing putting me off implementing this is the fact that `magit` doesn't really follow the notion of _marking_ files/issues (items) etc. The multiple selection is achieved by _highlighting/marking a region_ of items, so any action we would perform on multiple items would need them to be ordered.

Which might be the case, but imagine you have

```
| #1 - I'm a bug
| #2 - I'm a feature
| #3 - I'm a bug
| #4 - I'm a feature
```

And you want to mark all the bugs with a `bug` label, you'd have to do them individually in this case anyway! Similarly if you wanted to add the feature issues to a milestone...

**Comment by AlexChesters** [comment]
Ahh does it? That's a shame :disappointed:

**Comment by domtronn** [comment]
I think it does! I've not found a way to _mark_ multiple things at once?

**Comment by AlexChesters** [comment]
Go on... @domtronn

**Comment by domtronn** [comment]
I've decided I'm not going to implement this - If this becomes a desired feature, feel free to reopen this.
