### ISSUE TITLE
Unable to view issues

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/magit-gh-issues.el#55]
When trying to load the issues I get the following error message:

```
eieio-default-superclass: Invalid slot name: "#<gh-user gh-user>", :avatar-url
```

Plz fix

**Comment by domtronn** [comment]
I think this is fixed now...

@AlexChesters, could you do a pull and let me know if this fixes the issue?

**Comment by AlexChesters** [comment]
I can confirm this fixes it :+1:
